# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""K8s integration test for row 18 — Stale Metadata After Source Death.

Sequence:
  1. Connect to mx-server:8000 via kubectl port-forward.
  2. Call ListSources(status_filter=READY); expect exactly 1 instance
     (the live source).
  3. Force-delete the source pod with --grace-period=0.
  4. Sleep MX_HEARTBEAT_TIMEOUT_SECS + MX_REAPER_SCAN_INTERVAL_SECS + buffer.
     With the compressed reaper knobs in mx-server-redis.yaml that's 30 + 10
     + 20 = 60s.
  5. Call ListSources(status_filter=READY) again; expect 0 instances. The
     server's reaper should have transitioned the dead source from READY to
     STALE, and the status_filter=READY query excludes STALE entries.

Backend-agnostic — the reaper logic is identical for Redis and K8s CRD
backends. This test runs against the Redis backend by virtue of how the
composite action wires the mx-server manifest, but the same assertions
would hold against K8s CRD if/when we matrix that in.

The proto stubs (p2p_pb2.py, p2p_pb2_grpc.py) are generated into the test
directory by the composite action's grpc_tools.protoc step before pytest
runs. We import them as top-level modules to avoid pulling in the full
modelexpress python package (which has torch / nixl deps that are heavy
to install just for two gRPC stubs).
"""

import subprocess
import time

import grpc

# Stubs are generated by the composite action into this directory before
# pytest runs (see run-mx-stale-metadata-test/action.yml — grpc_tools.protoc).
# Pytest's conftest.py discovery adds ci/k8s/client/ to sys.path automatically,
# so a plain `import p2p_pb2_grpc` resolves regardless of the working directory.
import p2p_pb2_grpc

from kube_utils import port_forward
from mx_sources import list_ready_sources_by_kind


# Safety margin on top of (heartbeat_timeout + reaper_scan_interval) so that
# even if the kill lands just after a reaper scan tick, we still observe the
# READY→STALE transition before checking. Sized at one extra scan interval's
# worth of slack — this is a test-only constant; reaper timing comes from the
# action via fixtures so the server config and the test stay aligned.
STALE_DETECTION_BUFFER_SECS = 20
# Weight publication is health-gated and checked by a background publisher
# every 30 seconds. Allow one additional interval for the source to appear.
SOURCE_PUBLICATION_TIMEOUT_SECS = 60

MX_SERVER_LOCAL_PORT = 18001
MX_SERVER_REMOTE_PORT = 8000

SOURCE_JOB_NAME = "mx-source"


def test_stale_metadata_excluded_after_heartbeat_timeout(
    namespace: str,
    heartbeat_timeout_secs: int,
    reaper_scan_interval_secs: int,
) -> None:
    """End-to-end staleness check.

    Run order (gated by `--tb=short` so the assertion message is the
    primary signal):
      - Wait for the health-gated publisher, then confirm exactly 1 READY source.
      - After kill + wait_secs: server returns 0 READY sources.

    `wait_secs` is computed from the fixture values that the composite
    action threads in from the same inputs it gave the deployed server,
    so the test's wait window always tracks the actual server config.

    If the second assertion fires with > 0 instances, the reaper isn't
    transitioning the dead source to STALE in time — could be a bug in
    the reaper, in the heartbeat path, or in the status_filter handling.
    """
    wait_secs = heartbeat_timeout_secs + reaper_scan_interval_secs + STALE_DETECTION_BUFFER_SECS
    with port_forward(namespace, "svc/mx-server", MX_SERVER_LOCAL_PORT, MX_SERVER_REMOTE_PORT) as port:
        channel = grpc.insecure_channel(f"localhost:{port}")
        stub = p2p_pb2_grpc.P2pServiceStub(channel)

        publication_deadline = time.monotonic() + SOURCE_PUBLICATION_TIMEOUT_SECS
        while True:
            live_weights, live_artifacts = list_ready_sources_by_kind(stub)
            if len(live_weights) == 1 or time.monotonic() >= publication_deadline:
                break
            time.sleep(2)

        print(
            f"[before-kill] {len(live_weights)} READY weight source(s): "
            f"{[s.worker_id for s in live_weights]}; "
            f"{len(live_artifacts)} READY artifact source(s): "
            f"{[s.worker_id for s in live_artifacts]}"
        )
        assert len(live_weights) == 1, (
            f"Expected exactly 1 READY weight source before kill, got {len(live_weights)}. "
            f"This means the source either never published or there are leftover "
            f"sources from a previous test run."
        )

        # Delete the Job so the controller cannot spawn a replacement, then
        # force-delete its pod. Do not wait for foreground cascading: on busy
        # vCluster runs, pod termination can outlive kubectl's timeout even
        # though the source process is already stopping, which is enough for
        # this heartbeat-staleness test.
        job_delete = subprocess.run(
            [
                "kubectl", "-n", namespace, "delete", "job", SOURCE_JOB_NAME,
                "--cascade=orphan", "--ignore-not-found", "--wait=false",
            ],
            capture_output=True, text=True, check=True, timeout=30,
        )
        pod_delete = subprocess.run(
            [
                "kubectl", "-n", namespace, "delete", "pod",
                "-l", f"job-name={SOURCE_JOB_NAME}",
                "--grace-period=0", "--force",
                "--ignore-not-found", "--wait=false",
            ],
            capture_output=True, text=True, check=True, timeout=30,
        )
        print(f"[kill-job] {job_delete.stdout.strip()}")
        print(f"[kill-pod] {pod_delete.stdout.strip()}")

        # Wait for the heartbeat-timeout + one reaper scan + a buffer scan.
        # The reaper polls on a fixed interval, so a missed deadline can
        # take up to one full scan to surface.
        print(
            f"[wait] sleeping {wait_secs}s for the reaper to mark the dead source STALE "
            f"(heartbeat={heartbeat_timeout_secs}s + scan={reaper_scan_interval_secs}s + buffer={STALE_DETECTION_BUFFER_SECS}s)..."
        )
        time.sleep(wait_secs)

        stale_weights, stale_artifacts = list_ready_sources_by_kind(stub)
        print(
            f"[after-wait] {len(stale_weights)} READY weight source(s): "
            f"{[s.worker_id for s in stale_weights]}; "
            f"{len(stale_artifacts)} READY artifact source(s): "
            f"{[s.worker_id for s in stale_artifacts]}"
        )
        assert len(stale_weights) == 0, (
            f"Expected 0 READY weight sources after {wait_secs}s with no live source, "
            f"got {len(stale_weights)}: {[s.worker_id for s in stale_weights]}. "
            f"The reaper failed to transition the dead source from READY → STALE "
            f"within the configured heartbeat window."
        )
        assert len(stale_artifacts) == 0, (
            f"Expected 0 READY artifact sources after {wait_secs}s with no live source, "
            f"got {len(stale_artifacts)}: {[s.worker_id for s in stale_artifacts]}. "
            f"The reaper failed to transition artifact sources from READY → STALE "
            f"within the configured heartbeat window."
        )
